---
- hosts: dev
  become: true
  tasks:
      - name: start the container
        docker_container:
          name: cicd
          image: "chinna0102/cicd"
          state: started
          published_ports:
              - 0.0.0.0:8082:8080
